import 'styled-components';

declare module 'styled-components' {
  export interface DefaultTheme {
    MSG_CONTENT_USER_BACK: string;
    MSG_CONTENT_USER_TEXT: string;
    MSG_CONTENT_AWAY_BACK: string;
    MSG_CONTENT_AWAY_TEXT: string;

    CHATBOX_INPUTGROUP_TEXTAREA: string;
    CHATBOX_INPUTGROUP_BG: string;
    CHATBOX_INPUTGROUP_BORDER_TOP: string;
    CHATBOX_INPUTGROUP_BTN: string;
    CHATBOX_BROADCAST_BG: string;
    CHATBOX_BROADCAST_TEXT: string;
    CHATBOX_PARTICIPANTSBOX_BG: string;
    CHATBOX_PARTICIPANTSBOX_BORDER: string;
    CHATBOX_PARTICIPANTSBOX_TEXT: string;
    CHATBOX_INTERNAL_BG: string;
    CHATBOX_PARTICIPANTS_TEXT: string;
    CHATBOX_URL: string;

    AGENDA_CONTAINER_BG: string;
    AGENDA_CONTAINER_DETAILED: string;
    AGENDA_CONTAINER_NOT_DETAILED: string;
    AGENDA_CONTAINER_NOT_VOTED: string;
  }
}

export const lightTheme = {
  MSG_CONTENT_USER_BACK: '#fec46c',
  MSG_CONTENT_USER_TEXT: '#000000',
  MSG_CONTENT_AWAY_BACK: '#f7f6f3',
  MSG_CONTENT_AWAY_TEXT: '#000000',

  CHATBOX_INPUTGROUP_TEXTAREA: '#444444',
  CHATBOX_INPUTGROUP_BG: '#fffbf0',
  CHATBOX_INPUTGROUP_BORDER_TOP: '#f2a024',
  CHATBOX_INPUTGROUP_BTN: '#f2a024',
  CHATBOX_BROADCAST_BG: '#111111cc',
  CHATBOX_BROADCAST_TEXT: '#ffffff',
  CHATBOX_PARTICIPANTSBOX_BG: '#ffffff',
  CHATBOX_PARTICIPANTSBOX_BORDER: '#f2a024',
  CHATBOX_PARTICIPANTSBOX_TEXT: '#000000',
  CHATBOX_INTERNAL_BG: '#ffffff',
  CHATBOX_PARTICIPANTS_TEXT: '#000000',
  CHATBOX_URL: '#595959',

  AGENDA_CONTAINER_BG: '#ffffff',
  AGENDA_CONTAINER_DETAILED: '#f2a024',
  AGENDA_CONTAINER_NOT_DETAILED: '#8c8c8c',
  AGENDA_CONTAINER_NOT_VOTED: '#8c8c8c',
};

export const darkTheme = {
  MSG_CONTENT_USER_BACK: '#E17D00',
  MSG_CONTENT_USER_TEXT: '#ffffff',
  MSG_CONTENT_AWAY_BACK: '#686868',
  MSG_CONTENT_AWAY_TEXT: '#ffffff',

  CHATBOX_INPUTGROUP_TEXTAREA: '#ffffff',
  CHATBOX_INPUTGROUP_BG: '#8C6C4F',
  CHATBOX_INPUTGROUP_BORDER_TOP: '#f2a024',
  CHATBOX_INPUTGROUP_BTN: '#f2a024',
  CHATBOX_BROADCAST_BG: '##111111cc',
  CHATBOX_BROADCAST_TEXT: '#ffffff',
  CHATBOX_PARTICIPANTSBOX_BG: '#4f4f4f',
  CHATBOX_PARTICIPANTSBOX_BORDER: '#f2a024',
  CHATBOX_PARTICIPANTSBOX_TEXT: '#ffffff',
  CHATBOX_INTERNAL_BG: '#5a5751',
  CHATBOX_PARTICIPANTS_TEXT: '#ffffff',
  CHATBOX_URL: '#dddddd',

  AGENDA_CONTAINER_BG: '#60574d',
  AGENDA_CONTAINER_DETAILED: '#f5c070',
  AGENDA_CONTAINER_NOT_DETAILED: '#bfbfbf',
  AGENDA_CONTAINER_NOT_VOTED: '#bfbfbf',
};
