import 'styled-components';

declare module 'styled-components' {
  export interface DefaultTheme {
    MSG_CONTENT_USER_BACK: string;
    MSG_CONTENT_USER_TEXT: string;
    MSG_CONTENT_AWAY_BACK: string;
    MSG_CONTENT_AWAY_TEXT: string;

    CHATBOX_INPUTGROUP_TEXTAREA: string;
    CHATBOX_INPUTGROUP_BG: string;
    CHATBOX_INPUTGROUP_BORDER_TOP: string;
    CHATBOX_INPUTGROUP_BTN: string;
    CHATBOX_BROADCAST_BG: string;
    CHATBOX_BROADCAST_TEXT: string;
    CHATBOX_PARTICIPANTSBOX_BG: string;
    CHATBOX_PARTICIPANTSBOX_BORDER: string;
    CHATBOX_PARTICIPANTSBOX_TEXT: string;
    CHATBOX_INTERNAL_BG: string;
    CHATBOX_PARTICIPANTS_TEXT: string;
    CHATBOX_URL: string;

    AGENDA_CONTAINER_BG: string;
    AGENDA_CONTAINER_DETAILED: string;
    AGENDA_CONTAINER_NOT_DETAILED: string;
    AGENDA_CONTAINER_NOT_VOTED: string;
  }
}

export const lightTheme = {
  MSG_CONTENT_USER_BACK: '#000000',
  MSG_CONTENT_USER_TEXT: '#000000',
  MSG_CONTENT_AWAY_BACK: '#000000',
  MSG_CONTENT_AWAY_TEXT: '#000000',

  CHATBOX_INPUTGROUP_TEXTAREA: '#000000',
  CHATBOX_INPUTGROUP_BG: '#000000',
  CHATBOX_INPUTGROUP_BORDER_TOP: '#000000',
  CHATBOX_INPUTGROUP_BTN: '#000000',
  CHATBOX_BROADCAST_BG: '#000000',
  CHATBOX_BROADCAST_TEXT: '#000000',
  CHATBOX_PARTICIPANTSBOX_BG: '#000000',
  CHATBOX_PARTICIPANTSBOX_BORDER: '#000000',
  CHATBOX_PARTICIPANTSBOX_TEXT: '#000000',
  CHATBOX_INTERNAL_BG: '#000000',
  CHATBOX_PARTICIPANTS_TEXT: '#000000',
  CHATBOX_URL: '#000000',

  AGENDA_CONTAINER_BG: '#000000',
  AGENDA_CONTAINER_DETAILED: '#000000',
  AGENDA_CONTAINER_NOT_DETAILED: '#000000',
  AGENDA_CONTAINER_NOT_VOTED: '#000000',
};

export const darkTheme = {
  MSG_CONTENT_USER_BACK: '#000000',
  MSG_CONTENT_USER_TEXT: '#000000',
  MSG_CONTENT_AWAY_BACK: '#000000',
  MSG_CONTENT_AWAY_TEXT: '#000000',

  CHATBOX_INPUTGROUP_TEXTAREA: '#000000',
  CHATBOX_INPUTGROUP_BG: '#000000',
  CHATBOX_INPUTGROUP_BORDER_TOP: '#000000',
  CHATBOX_INPUTGROUP_BTN: '#000000',
  CHATBOX_BROADCAST_BG: '#000000',
  CHATBOX_BROADCAST_TEXT: '#000000',
  CHATBOX_PARTICIPANTSBOX_BG: '#000000',
  CHATBOX_PARTICIPANTSBOX_BORDER: '#000000',
  CHATBOX_PARTICIPANTSBOX_TEXT: '#000000',
  CHATBOX_INTERNAL_BG: '#000000',
  CHATBOX_PARTICIPANTS_TEXT: '#000000',
  CHATBOX_URL: '#000000',

  AGENDA_CONTAINER_BG: '#000000',
  AGENDA_CONTAINER_DETAILED: '#000000',
  AGENDA_CONTAINER_NOT_DETAILED: '#000000',
  AGENDA_CONTAINER_NOT_VOTED: '#000000',
};
